#define __AM18X_MAP_H__
#define _EXTERN		extern
#define MODULE_NR_PER_PSC	32
#define PTCMD_GO1			(0x1 << 1)
#define PTCMD_GO0			(0x1 << 0)
#define PTSTAT_GO1_MASK			(0x1 << 1)
#define PTSTAT_GO1_no			(0x0 << 1)
#define PTSTAT_GO1_yes			(0x1 << 1)
#define PTSTAT_GO0_MASK			(0x1 << 0)
#define PTSTAT_GO0_no			(0x0 << 0)
#define PTSTAT_GO0_yes			(0x1 << 0)
#define PDSTATx_EMUIHB_MASK		(0x1 << 11)
#define PDSTATx_EMUIHB_unactive		(0x0 << 11)
#define PDSTATx_EMUIHB_active		(0x1 << 11)
#define PDSTATx_PORDONE_MASK		(0x1 << 9)
#define PDSTATx_PORDONE_no		(0x0 << 9)
#define PDSTATx_PORDONE_yes		(0x1 << 9)
#define PDSTATx_POR_MASK		(0x1 << 8)
#define PDSTATx_POR_asserted		(0x0 << 8)
#define PDSTATx_POR_deasserted		(0x1 << 8)
#define PDSTATx_STATE_MASK		(0x1F << 0)
#define PDSTATx_STATE_off		(0x0 << 0)
#define PDSTATx_STATE_on		(0x1 << 0)
#define PDSTATx_STATE_in_transition(x)	(0x10 <= (x) && (x) <= 0x1A)
#define PDCTLx_WAKECNT_MASK		(0xFF << 16)
#define PDCTLx_GOOD2ACCESS_MASK		(0xF << 20)
#define PDCTLx_ON2GOOD_MASK		(0xF << 16)
#define PDCTLx_PDMODE_MASK		(0xF << 12)
#define PDCTLx_PDMODE_on		(0xF << 12)
#define PDCTLx_EMUIHBIE_MASK		(0x1 << 9)
#define PDCTLx_EMUIHBIE_disable		(0x0 << 9)
#define PDCTLx_EMUIHBIE_enable		(0x1 << 9)
#define PDCTLx_NEXT_MASK		(0x1 << 0)
#define PDCTLx_NEXT_off			(0x0 << 0)
#define PDCTLx_NEXT_on			(0x1 << 0)
#define PDCFGx_PD_LOCK_MASK		(0x1 << 3)
#define PDCFGx_PD_LOCK_locked		(0x0 << 3)
#define PDCFGx_PD_LOCK_unlocked		(0x1 << 3)
#define PDCFGx_ICEPICK_MASK		(0x1 << 2)
#define PDCFGx_ICEPICK_unpresent	(0x0 << 2)
#define PDCFGx_ICEPICK_present		(0x1 << 2)
#define PDCFGx_RAM_PSM_MASK		(0x1 << 1)
#define PDCFGx_RAM_PSM_no		(0x0 << 1)
#define PDCFGx_RAM_PSM_yes		(0x1 << 1)
#define PDCFGx_ALWAYSON_MASK		(0x1 << 0)
#define PDCFGx_ALWAYSON_no		(0x0 << 0)
#define PDCFGx_ALWAYSON_yes		(0x1 << 0)
#define MDSTATx_EMUIHB_MASK		(0x1 << 17)
#define MDSTATx_EMUIHB_no		(0x0 << 17)
#define MDSTATx_EMUIHB_yes		(0x1 << 17)
#define MDSTATx_EMURST_MASK		(0x1 << 16)
#define MDSTATx_EMURST_no		(0x0 << 16)
#define MDSTATx_EMURST_yes		(0x1 << 16)
#define MDSTATx_MCKOUT_MASK		(0x1 << 12)
#define MDSTATx_MCKOUT_off		(0x0 << 12)
#define MDSTATx_MCKOUT_on		(0x1 << 12)
#define MDSTATx_MRST_MASK		(0x1 << 10)
#define MDSTATx_MRST_asserted		(0x0 << 10)
#define MDSTATx_MRST_deasserted		(0x1 << 10)
#define MDSTATx_LRSTDONE_MASK		(0x1 << 9)
#define MDSTATx_LRSTDONE_yes		(0x0 << 9)
#define MDSTATx_LRSTDONE_no		(0x1 << 9)
#define MDSTATx_LRST_MASK		(0x1 << 8)
#define MDSTATx_LRST_asserted		(0x0 << 8)
#define MDSTATx_LRST_deasserted		(0x1 << 8)
#define MDSTATx_STATE_MASK		(0x3F << 0)
#define MDSTATx_STATE_SwRstDisable	(0x0)
#define MDSTATx_STATE_SyncReset		(0x1)
#define MDSTATx_STATE_Disable		(0x2)
#define MDSTATx_STATE_Enable		(0x3)
#define MDSTATx_STATE_in_transition(x)	(0x4 <= (x) && (x) <= 0x3F)
#define MDCTLx_FORCE_MASK		(0x1 << 31)
#define MDCTLx_FORCE_disabled		(0x0 << 31)
#define MDCTLx_FORCE_enabled		(0x1 << 31)
#define MDCTLx_EMUIHBIE_MASK		(0x1 << 10)
#define MDCTLx_EMUIHBIE_disable		(0x0 << 10)
#define MDCTLx_EMUIHBIE_enable		(0x1 << 10)
#define MDCTLx_EMURSTIE_MASK		(0x1 << 9)
#define MDCTLx_EMURSTIE_disable		(0x0 << 9)
#define MDCTLx_EMURSTIE_enable		(0x1 << 9)
#define MDCTLx_LRST_MASK		(0x1 << 8)
#define MDCTLx_LRST_assert		(0x0 << 8)
#define MDCTLx_LRST_deassert		(0x1 << 8)
#define MDCTLx_STATE_MASK		(0x7 << 0)
#define MDCTLx_STATE_SwRstDisable	(0x0 << 0)
#define MDCTLx_STATE_SyncReset		(0x1 << 0)
#define MDCTLx_STATE_Disable		(0x2 << 0)
#define MDCTLx_STATE_Enable		(0x3 << 0)
#define KICK0R_UNLOCK			0x83E70B13
#define KICK0R_LOCK			0x00000000
#define KICK1R_UNLOCK			0x95A4F1E0
#define KICK1R_LOCK			0x00000000
#define HOST0CFG_BOOTRDY_MASK		(0x1 << 0)
#define HOST0CFG_BOOTRDY_reset		(0x0 << 0)
#define HOST0CFG_BOOTRDY_released	(0x1 << 0)
#define IRAWSTAT_ADDRERR_MASK		(0x1 << 1)
#define IRAWSTAT_ADDRERR_unset		(0x0 << 1)
#define IRAWSTAT_ADDRERR_set		(0x1 << 1)
#define IRAWSTAT_PROTERR_MASK		(0x1 << 0)
#define IRAWSTAT_PROTERR_unset		(0x0 << 0)
#define IRAWSTAT_PROTERR_set		(0x1 << 0)
#define IENSTAT_ADDRERR_MASK		(0x1 << 1)
#define IENSTAT_ADDRERR_unset		(0x0 << 1)
#define IENSTAT_ADDRERR_set		(0x1 << 1)
#define IENSTAT_PROTERR_MASK		(0x1 << 0)
#define IENSTAT_PROTERR_unset		(0x0 << 0)
#define IENSTAT_PROTERR_set		(0x1 << 0)
#define IENSET_ADDRERR_EN_enable	(0x1 << 1)
#define IENSET_PROTERR_EN_enable	(0x1 << 0)
#define IENCLR_ADDRERR_EN_enable	(0x1 << 1)
#define IENCLR_PROTERR_EN_enable	(0x1 << 0)
#define EOI_EOIVECT_MASK		(0xFF << 0)
#define FLTSTAT_ID_MASK			(0xFF << 24)
#define FLTSTAT_MSTID_MASK		(0xFF << 16)
#define FLTSTAT_PRIVID_MASK		(0xF << 9)
#define FLTSTAT_TYPE_MASK		(0x3F << 0)
#define FLTSTAT_TYPE_None		0x0
#define FLTSTAT_TYPE_UserExec		0x1
#define FLTSTAT_TYPE_UserWrite		0x2
#define FLTSTAT_TYPE_UserRead		0x4
#define FLTSTAT_TYPE_SupervisorExec	0x8
#define FLTSTAT_TYPE_SupervisorWrite	0x10
#define FLTSTAT_TYPE_SupervisorRead	0x20
#define RBR_DATA_MASK			0xFF
#define THRw				RBRr
#define THR_DATA_MASK			0xFF
#define IER_EDSSI_MASK			(0x1 << 3)
#define IER_EDSSI_disable		(0x0 << 3)
#define IER_EDSSI_enable		(0x1 << 3)
#define IER_ELSI_MASK			(0x1 << 2)
#define IER_ELSI_disable		(0x0 << 2)
#define IER_ELSI_enable			(0x1 << 2)
#define IER_ETBEI_MASK			(0x1 << 1)
#define IER_ETBEI_disable		(0x0 << 1)
#define IER_ETBEI_enable		(0x1 << 1)
#define IER_ERBI_MASK			(0x1 << 0)
#define IER_ERBI_disable		(0x0 << 0)
#define IER_ERBI_enable			(0x1 << 0)
#define IIR_FIFOEN_MASK			(0x3 << 6)
#define IIR_FIFOEN_Non_FIFO		(0x0 << 6)
#define IIR_FIFOEN_enabled		(0x3 << 6)
#define IIR_INTID_MASK			(0x7 << 1)
#define IIR_INTID_thr_empty		(0x1 << 1)
#define IIR_INTID_data_avail		(0x2 << 1)
#define IIR_INTID_line_status		(0x3 << 1)
#define IIR_INTID_timeout		(0x6 << 1)
#define IIR_IPEND_MASK			(0x1 << 0)
#define IIR_IPEND_yes			(0x0 << 0)
#define IIR_IPEND_no			(0x1 << 0)
#define FCRw		IIRr
#define FCR_RXFIFTL_MASK		(0x3 << 6)
#define FCR_RXFIFTL_1byte		(0x0 << 6)
#define FCR_RXFIFTL_4bytes		(0x1 << 6)
#define FCR_RXFIFTL_8bytes		(0x2 << 6)
#define FCR_RXFIFTL_14bytes		(0x3 << 6)
#define FCR_DMAMODE1_MASK		(0x1 << 3)
#define FCR_DMAMODE1_disable		(0x0 << 3)
#define FCR_DMAMODE1_enable		(0x1 << 3)
#define FCR_TXCLR_MASK			(0x1 << 2)
#define FCR_TXCLR_clear			(0x1 << 2)
#define FCR_RXCLR_MASK			(0x1 << 1)
#define FCR_RXCLR_clear			(0x1 << 1)
#define FCR_FIFOEN_MASK			(0x1 << 0)
#define FCR_FIFOEN_No			(0x0 << 0)
#define FCR_FIFOEN_Yes			(0x1 << 0)
#define LCR_DLAB_MASK			(0x1 << 7)
#define LCR_DLAB_rbr_thr_ier		(0x0 << 7)
#define LCR_DLAB_dll_dlh		(0x1 << 7)
#define LCR_BC_MASK			(0x1 << 6)
#define LCR_BC_disabled			(0x0 << 6)
#define LCR_BC_enabled			(0x1 << 6)
#define LCR_SP_MASK			(0x1 << 5)
#define LCR_SP_disabled			(0x0 << 5)
#define LCR_SP_enabled			(0x1 << 5)
#define LCR_EPS_MASK			(0x1 << 4)
#define LCR_EPS_Odd			(0x0 << 4)
#define LCR_EPS_Even			(0x1 << 4)
#define LCR_PEN_MASK			(0x1 << 3)
#define LCR_PEN_No			(0x0 << 3)
#define LCR_PEN_Yes			(0x1 << 3)
#define LCR_STB_MASK			(0x1 << 2)
#define LCR_STB_1STOP			(0x0 << 2)
#define LCR_STB_15_2STOP		(0x1 << 2)
#define LCR_WLS_MASK			(0x3 << 0)
#define LCR_WLS_5bits			(0x0 << 0)
#define LCR_WLS_6bits			(0x1 << 0)
#define LCR_WLS_7bits			(0x2 << 0)
#define LCR_WLS_8bits			(0x3 << 0)
#define MCR_AFE_MASK			(0x1 << 5)
#define MCR_AFE_disabled		(0x0 << 5)
#define MCR_AFE_enabled			(0x1 << 5)
#define MCR_LOOP_MASK			(0x1 << 4)
#define MCR_LOOP_disabled		(0x0 << 4)
#define MCR_LOOP_enabled		(0x1 << 4)
#define MCR_RTS_MASK			(0x1 << 1)
#define MCR_RTS_disabled		(0x0 << 1)
#define MCR_RTS_enabled			(0x1 << 1)
#define LSR_RXFIFOE_MASK		(0x1 << 7)
#define LSR_RXFIFOE_no_error		(0x0 << 7)
#define LSR_RXFIFOE_error		(0x1 << 7)
#define LSR_TEMT_MASK			(0x1 << 6)
#define LSR_TEMT_no			(0x0 << 6)
#define LSR_TEMT_yes			(0x1 << 6)
#define LSR_THRE_MASK			(0x1 << 5)
#define LSR_THRE_no			(0x0 << 5)
#define LSR_THRE_yes			(0x1 << 5)
#define LSR_BI_MASK			(0x1 << 4)
#define LSR_BI_no			(0x0 << 4)
#define LSR_BI_yes			(0x1 << 4)
#define LSR_FE_MASK			(0x1 << 3)
#define LSR_FE_no			(0x0 << 3)
#define LSR_FE_yes			(0x1 << 3)
#define LSR_PE_MASK			(0x1 << 2)
#define LSR_PE_no			(0x0 << 2)
#define LSR_PE_yes			(0x1 << 2)
#define LSR_OE_MASK			(0x1 << 1)
#define LSR_OE_no			(0x0 << 1)
#define LSR_OE_yes			(0x1 << 1)
#define LSR_DR_MASK			(0x1 << 0)
#define LSR_DR_no			(0x0 << 0)
#define LSR_DR_yes			(0x1 << 0)
#define MSR_CD_MASK			(0x1 << 7)
#define MSR_CD_high			(0x0 << 7)
#define MSR_CD_low			(0x1 << 7)
#define MSR_RI_MASK			(0x1 << 6)
#define MSR_RI_high			(0x0 << 6)
#define MSR_RI_low			(0x1 << 6)
#define MSR_DSR_MASK			(0x1 << 5)
#define MSR_DSR_high			(0x0 << 5)
#define MSR_DSR_low			(0x1 << 5)
#define MSR_CTS_MASK			(0x1 << 4)
#define MSR_CTS_high			(0x0 << 4)
#define MSR_CTS_low			(0x1 << 4)
#define MSR_DCD_MASK			(0x1 << 3)
#define MSR_DCD_unchanged		(0x0 << 3)
#define MSR_DCD_changed			(0x1 << 3)
#define MSR_TERI_MASK			(0x1 << 2)
#define MSR_TERI_unchanged		(0x0 << 2)
#define MSR_TERI_changed		(0x1 << 2)
#define MSR_DDSR_MASK			(0x1 << 1)
#define MSR_DDSR_unchanged		(0x0 << 1)
#define MSR_DDSR_changed		(0x1 << 1)
#define MSR_DCTS_MASK			(0x1 << 0)
#define MSR_DCTS_unchanged		(0x0 << 0)
#define MSR_DCTS_changed		(0x1 << 0)
#define SCR_MASK			0xFF
#define PWREMU_UTRST_MASK		(0x1 << 14)
#define PWREMU_UTRST_reset		(0x0 << 14)
#define PWREMU_UTRST_enabled		(0x1 << 14)
#define PWREMU_URRST_MASK		(0x1 << 13)
#define PWREMU_URRST_reset		(0x0 << 13)
#define PWREMU_URRST_enabled		(0x1 << 13)
#define PWREMU_FREE_MASK		(0x1 << 0)
#define PWREMU_FREE_halt		(0x0 << 0)
#define PWREMU_FREE_run			(0x1 << 0)
#define MDR_OSM_SEL_MASK		(0x1 << 0)
#define MDR_OSM_SEL_16x			(0x0 << 0)
#define MDR_OSM_SEL_13x			(0x1 << 0)
#define PSC0_BASE			0x01C10000
#define SYSCFG0_BASE			0x01C14000
#define UART0_BASE			0x01C42000
#define UART1_BASE			0x01D0C000
#define UART2_BASE			0x01D0D000
#define PSC1_BASE			0x01E27000
#define SYSCFG1_BASE			0x01E2C000
